run_name: 'dataset_2_linear'
logdir: './logs/'
wandb_params:
  mode: 'online'  # disabled, offline, online
  entity: 'siemteusink'
  group: 'hla_a_linear_noise'
dataset: 'pmhc'
datadir: './data/pmhc/ca/'
enable_progress_bar: False
num_sanity_val_steps: 0

mode: 'pocket_conditioning'
pocket_representation: 'CA'
batch_size: 32
lr: 5.0e-4
n_epochs: 2000
num_workers: 18
gpus: 1
clip_grad: True
augment_rotation: False
augment_noise: 0

auxiliary_loss: False
loss_params:
  max_weight: 1.0
  schedule: 'linear'
  clamp_lj: 3.0

egnn_params:
  device: 'cuda'
  edge_cutoff: null
  joint_nf: 32
  hidden_nf: 64
  n_layers: 3
  attention: True
  tanh: False
  norm_constant: 1
  inv_sublayers: 1
  sin_embedding: True
  sin_encoding: True
  aggregation_method: 'sum'
  use_nodes_noise_prediction: True
  normalization_factor: 100  # used if aggregation_method='sum'

diffusion_params:
  diffusion_steps: 1000
  diffusion_noise_schedule: 'polynomial_2'
  diffusion_noise_precision: 1.0e-4
  diffusion_loss_type: 'l2'
  normalize_factors: [1, 2]  # [x, h]

eval_epochs: 100
visualize_sample_epoch: 75
visualize_chain_epoch: 10
eval_params:
  n_eval_samples: 10
  eval_batch_size: 32
  smiles_file:
  n_visualize_samples: 5
  keep_frames: 100